/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedTableViewRouteImport } from './routes/(authed)/table-view'
import { Route as authedDashboardRouteImport } from './routes/(authed)/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTableViewRoute = authedTableViewRouteImport.update({
  id: '/(authed)/table-view',
  path: '/table-view',
  getParentRoute: () => rootRouteImport,
} as any)
const authedDashboardRoute = authedDashboardRouteImport.update({
  id: '/(authed)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authedDashboardRoute
  '/table-view': typeof authedTableViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof authedDashboardRoute
  '/table-view': typeof authedTableViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)/dashboard': typeof authedDashboardRoute
  '/(authed)/table-view': typeof authedTableViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/table-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/table-view'
  id: '__root__' | '/' | '/(authed)/dashboard' | '/(authed)/table-view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedDashboardRoute: typeof authedDashboardRoute
  authedTableViewRoute: typeof authedTableViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/table-view': {
      id: '/(authed)/table-view'
      path: '/table-view'
      fullPath: '/table-view'
      preLoaderRoute: typeof authedTableViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/dashboard': {
      id: '/(authed)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedDashboardRoute: authedDashboardRoute,
  authedTableViewRoute: authedTableViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
