#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
LOCAL_CADDY_FILE="$SCRIPT_DIR/caddy/Caddyfile.local"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

FRITZBOX_DEVICE_HOSTNAME="${FRITZBOX_DEVICE_HOSTNAME:-}"

cat > "$LOCAL_CADDY_FILE" <<'EOF'
# Auto-generated by infra/generate-caddy-local.sh
# Do not commit machine-specific hostnames.
EOF

if [[ -z "$FRITZBOX_DEVICE_HOSTNAME" ]]; then
  echo "No FRITZBOX_DEVICE_HOSTNAME configured. Created empty local Caddy config."
  exit 0
fi

cat >> "$LOCAL_CADDY_FILE" <<EOF

# FRITZ!Box hostname routing (LAN)
# Example URL: https://${FRITZBOX_DEVICE_HOSTNAME}:8449 -> sst dev
${FRITZBOX_DEVICE_HOSTNAME}:8447 {
  tls internal
  reverse_proxy host.docker.internal:3057
}

${FRITZBOX_DEVICE_HOSTNAME}:8448 {
  tls internal
  reverse_proxy host.docker.internal:3058
}

${FRITZBOX_DEVICE_HOSTNAME}:8449 {
  tls internal
  reverse_proxy host.docker.internal:3059
}

${FRITZBOX_DEVICE_HOSTNAME}:9447 {
  tls internal
  reverse_proxy host.docker.internal:4057
}

${FRITZBOX_DEVICE_HOSTNAME}:9448 {
  tls internal
  reverse_proxy host.docker.internal:4058
}

${FRITZBOX_DEVICE_HOSTNAME}:9449 {
  tls internal
  reverse_proxy host.docker.internal:4059
}

${FRITZBOX_DEVICE_HOSTNAME}:8450 {
  tls internal
  reverse_proxy host.docker.internal:3070
}

${FRITZBOX_DEVICE_HOSTNAME}:9450 {
  tls internal
  reverse_proxy host.docker.internal:4070
}
EOF

echo "Generated $LOCAL_CADDY_FILE for FRITZBOX_DEVICE_HOSTNAME=$FRITZBOX_DEVICE_HOSTNAME"
