import { createServerFn } from "@tanstack/react-start"
import { z } from "zod"

import { textImprovementEnvSchema } from "@/contracts/text-improvement-env"
import {
  type ImproveTextResult,
  processTabRecordingInputSchema,
} from "@/contracts/tab-sync"

const DEFAULT_WHISPER_MODEL_ID = "whisper-unknown" as const
const DEFAULT_LANGUAGE = "de" as const
const UPLOAD_FILE_NAME = "audio.wav" as const

const whisperVerboseJsonResponseSchema = z.object({
  text: z.string().optional(),
  model: z.string().optional(),
  error: z.string().optional(),
})

const ollamaGenerateResponseSchema = z.object({
  model: z.string().optional(),
  response: z.string().optional(),
  error: z.string().optional(),
})

function readTextImprovementEnv() {
  return textImprovementEnvSchema.parse({
    SST_WHISPER_ENDPOINT: process.env.SST_WHISPER_ENDPOINT,
    SST_OLLAMA_ENDPOINT: process.env.SST_OLLAMA_ENDPOINT,
    SST_OLLAMA_MODEL_ID: process.env.SST_OLLAMA_MODEL_ID,
  })
}

function parseRecordingFormData(formData: FormData) {
  const recordingInput = processTabRecordingInputSchema.parse({
    tabId: formData.get("tabId"),
    contextText: formData.get("contextText"),
    language: formData.get("language") ?? undefined,
  })

  const fileEntry = formData.get("file")

  if (!(fileEntry instanceof Blob) || fileEntry.size === 0) {
    throw new Error("Audio file is required.")
  }

  return {
    ...recordingInput,
    audioBlob: fileEntry,
  }
}

function normalizeWhisperText(text: string) {
  const withoutSplitWords = text.replace(
    /([A-Za-zÄÖÜäöüß])\r?\n([A-Za-zÄÖÜäöüß])/g,
    "$1$2",
  )

  return withoutSplitWords.replace(/\s+/g, " ").trim()
}

function buildCorrectionPrompt(input: {
  transcriptionText: string
  contextText: string
}) {
  return [
    "You are an assistant tasked with improving the transcribed text from an ASR model. Replace spoken characters such as 'parentheses', 'colon', 'period', etc., with their corresponding symbols. Correct spelling. Make as few changes as possible — only what is necessary. You will receive the user’s current transcript as context to help you understand what it’s about. Then improve the text generated by the ASR model. Change only words that don’t make sense in the sentence and where you can find a better word based on the context — one **that sounds phonetically similar** but wasn’t correctly recognized by the ASR model. If you find a better word that isn't phonetically similar, DON'T use it! Output ONLY the improved text. NOT the complete transcript. NO explanations.",
    "Context:",
    input.contextText.trim().length > 0 ? input.contextText : "(nothing yet)",
    "",
    "Text to correct:",
    input.transcriptionText,
  ].join("\n")
}

async function transcribeWithWhisper(input: {
  whisperEndpoint: string
  audioBlob: Blob
  language: string
}): Promise<{ text: string; modelId: string }> {
  const formData = new FormData()

  formData.append("file", input.audioBlob, UPLOAD_FILE_NAME)
  formData.append("response_format", "verbose_json")
  formData.append("language", input.language)
  formData.append("temperature", "0.0")

  const response = await fetch(input.whisperEndpoint, {
    method: "POST",
    body: formData,
  })

  if (!response.ok) {
    const responseText = await response.text()
    throw new Error(
      `Whisper request failed (${response.status}): ${responseText}`,
    )
  }

  const rawResponseData: unknown = await response.json()
  const data = whisperVerboseJsonResponseSchema.parse(rawResponseData)
  const rawText = data.text?.trim()

  if (!rawText) {
    throw new Error(data.error ?? "Whisper response does not include text.")
  }

  return {
    text: normalizeWhisperText(rawText),
    modelId: data.model ?? DEFAULT_WHISPER_MODEL_ID,
  }
}

async function correctWithOllama(input: {
  ollamaEndpoint: string
  ollamaModelId: string
  transcriptionText: string
  contextText: string
}): Promise<{ text: string; modelId: string }> {
  const modelId = input.ollamaModelId
  const prompt = buildCorrectionPrompt(input)

  const response = await fetch(input.ollamaEndpoint, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: modelId,
      prompt,
      stream: false,
    }),
  })

  if (!response.ok) {
    const responseText = await response.text()
    throw new Error(
      `Ollama request failed (${response.status}): ${responseText}`,
    )
  }

  const rawResponseData: unknown = await response.json()
  const data = ollamaGenerateResponseSchema.parse(rawResponseData)
  const correctedText = data.response?.trim()

  if (!correctedText) {
    throw new Error(data.error ?? "Ollama response does not include text.")
  }

  return {
    text: correctedText,
    modelId: data.model ?? modelId,
  }
}

export const improveTabRecordingFn = createServerFn({ method: "POST" })
  .inputValidator((data) => z.instanceof(FormData).parse(data))
  .handler(async ({ data }) => {
    const env = readTextImprovementEnv()
    const recordingInput = parseRecordingFormData(data)

    const transcriptionStartAtMs = Date.now()
    const transcriptionResult = await transcribeWithWhisper({
      whisperEndpoint: env.SST_WHISPER_ENDPOINT,
      audioBlob: recordingInput.audioBlob,
      language: recordingInput.language ?? DEFAULT_LANGUAGE,
    })
    const transcriptionDurationMs = Date.now() - transcriptionStartAtMs

    const correctionStartAtMs = Date.now()
    const correctionResult = await correctWithOllama({
      ollamaEndpoint: env.SST_OLLAMA_ENDPOINT,
      ollamaModelId: env.SST_OLLAMA_MODEL_ID,
      transcriptionText: transcriptionResult.text,
      contextText: recordingInput.contextText,
    })
    const correctionDurationMs = Date.now() - correctionStartAtMs

    const improveTextResult: ImproveTextResult = {
      tabId: recordingInput.tabId,
      rawTranscriptionText: transcriptionResult.text,
      correctedText: correctionResult.text,
      whisperModelId: transcriptionResult.modelId,
      ollamaModelId: correctionResult.modelId,
      transcriptionDurationMs,
      correctionDurationMs,
      totalDurationMs: transcriptionDurationMs + correctionDurationMs,
    }

    return improveTextResult
  })
